/**
 * Generates dist/_headers after the Astro build.
 *
 * The CSP for HTML pages needs a hash for every inline <script> Astro emits
 * (there is one: the reduced-motion bootstrap in Base.astro). Hashing at build
 * time keeps script-src free of 'unsafe-inline' without needing a server.
 *
 * Note: _headers only applies to responses served from the assets binding.
 * Responses generated by worker/index.ts set their own headers.
 */
import { createHash } from 'node:crypto';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { join, extname } from 'node:path';

const DIST = 'dist';

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else if (extname(entry.name) === '.html') out.push(full);
  }
  return out;
}

const files = await walk(DIST);
const hashes = new Set();

for (const file of files) {
  const html = await readFile(file, 'utf8');
  // Inline scripts only: anything with a src= attribute is external.
  const pattern = /<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi;
  let match;
  while ((match = pattern.exec(html)) !== null) {
    const body = match[1];
    if (!body.trim()) continue;
    // JSON-LD is data, not script execution, and needs no hash.
    if (/type=["']application\/ld\+json["']/i.test(match[0])) continue;
    hashes.add(`'sha256-${createHash('sha256').update(body, 'utf8').digest('base64')}'`);
  }
}

const TURNSTILE = 'https://challenges.cloudflare.com';

const csp = [
  "default-src 'none'",
  `script-src 'self' ${TURNSTILE} ${[...hashes].join(' ')}`.trim(),
  // Stylesheets are external; style-src-attr covers the inline style="--i:0"
  // custom properties the layout uses for staggering.
  "style-src 'self'",
  "style-src-attr 'unsafe-inline'",
  "img-src 'self' data:",
  "font-src 'self'",
  `connect-src 'self' ${TURNSTILE}`,
  `frame-src ${TURNSTILE}`,
  "form-action 'self'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
  "object-src 'none'",
  "manifest-src 'self'",
  'upgrade-insecure-requests',
].join('; ');

const headers = `# Generated by scripts/build-headers.mjs — do not edit dist/_headers by hand.
# Applies to static asset responses only; worker/index.ts sets its own headers.

/*
  Content-Security-Policy: ${csp}
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), microphone=(), payment=(), usb=(), interest-cohort=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  X-Frame-Options: DENY

# Fingerprinted build output can be cached hard.
/_assets/*
  Cache-Control: public, max-age=31536000, immutable

/fonts/*
  Cache-Control: public, max-age=31536000, immutable
  Access-Control-Allow-Origin: *

/og/*
  Cache-Control: public, max-age=604800

/.well-known/security.txt
  Content-Type: text/plain; charset=utf-8
`;

await writeFile(join(DIST, '_headers'), headers, 'utf8');
console.log(`[headers] wrote dist/_headers with ${hashes.size} inline-script hash(es)`);
